import type { AuditResult } from "@/types";
import { formatCurrency } from "@/lib/utils";

interface AISummaryBlockProps {
  result: AuditResult;
}

function buildFallbackSummary(result: AuditResult): string {
  const { formData, totalMonthlySavings, totalAnnualSavings, toolResults, savingsTier } = result;
  const toolCount = formData.tools.length;

  if (savingsTier === "optimal") {
    return `Your team of ${formData.teamSize} is running a well-optimised AI stack across ${toolCount} tool${toolCount !== 1 ? "s" : ""}. Current plans match your ${formData.useCase} use case and seat count. No plan mismatches or seat overages detected. Check back when you add new tools or your team grows.`;
  }

  const topResult = [...toolResults]
    .filter((r) => r.monthlySavings > 0)
    .sort((a, b) => b.monthlySavings - a.monthlySavings)[0];

  return `Your team of ${formData.teamSize} is spending on ${toolCount} AI tool${toolCount !== 1 ? "s" : ""} with ${formatCurrency(totalMonthlySavings)}/month — ${formatCurrency(totalAnnualSavings)}/year — in identified savings. The biggest opportunity is ${topResult?.toolName ?? "a plan adjustment"}: ${topResult?.reasoning ?? "consider reviewing your current plan"}. Review the recommendations below and action the highest-savings items first.`;
}

export function AISummaryBlock({ result }: AISummaryBlockProps) {
  const summary = result.aiSummary ?? buildFallbackSummary(result);
  const isAI = !!result.aiSummary;

  return (
    <div className="card p-5 bg-surface-card/60">
      <div className="flex items-center gap-2 mb-3">
        <span className="text-base">🔮</span>
        <span className="text-xs font-medium text-slate-400 uppercase tracking-wide">
          {isAI ? "AI Summary" : "Audit Summary"}
        </span>
        {isAI && (
          <span className="text-xs text-brand-400/60 ml-auto">
            Generated by Claude
          </span>
        )}
      </div>
      <p className="text-slate-300 text-sm leading-relaxed">{summary}</p>
    </div>
  );
}
